const AppRoutes = {
    profile_dashboard: "/user/dashboard",
    profile_orders: "/user/orders",
    profile_delivery_details: "/user/delivery_details",
    profile_saved_items: "/user/saved_items",
    // profile_dashboard: "/user/",
    signin: "/signin",
    signup: "/signup",
    signout: "/signout",
    send_mail: "/resetsendmail",
    mail_sent: "/mailsent",
    reset_password: "/resetpassword",
    password_reset: "/passwordreset",
    reset_send_mail: "/resetsendmail",
    privacy_policy: "/privacy_policy",
    //products
    tables: "/tables",
    shop: "/shop",
    product: "/products/:categoryName",
    search_product_name: "/search/:productName",
    all_products: "/allproducts",
    collections: "/collections",
    checkout: "/checkout",
    checkout_success: "/checkout-success",
    cart: "/cart",
    product_detail: "/product_detail",
    story: "/story",
    faqs: "/faqs",
    blog: "/blog",
    returns_policy: "/returns_policy",
    portfolio: "/portfolio/:companyName/:companyId",
    media: "/media",
    contact_us: "/contact_us",
    assembly: "/assembly",
    terms: "/terms",
    accessibility: "/accessibility",
    sitemap: "/sitemap",
}

export default AppRoutes;